InternTestWebApp/Models/ErrorViewModel.cs
namespace InternTestWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InternTestWebApp/Models/SalesOrders.cs
using System.ComponentModel.DataAnnotations;

namespace InternTestWebApp.Models
{
    public class SalesOrders
    {
        [Key]
        public int Id { set; get; }
        [Required]
        [Display(Name = "Sales Order")]
        public string SalesOrder { set; get; }
        [Required]
        [Display(Name = "Sales Order Item")]
        public string SalesOrderItem { set; get; }
        [Required]
        [Display(Name = "Work Order")]
        public string WorkOrder { set; get; }
        [Required]
        [Display(Name = "Product ID")]
        public string ProductID { set; get; }
        [Required]
        [Display(Name = "Product Description")]
        public string ProductDescription { set; get; }
        [Required]
        [Display(Name = "Order Quantity")]
        public decimal OrderQuantity { set; get; }
        [Required]
        [Display(Name = "Order Status")]
        public string OrderStatus { set; get; }
        [Required]
        public DateTime Timestamp { set; get; }
    }
}

InternTestWebApp/Controllers/HomeController.cs
using InternTestWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace InternTestWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

InternTestWebApp/Controllers/SalesOrdersController.cs
using InternTestWebApp.Models;
using InternTestWebApp.Repository.cs;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace InternTestWebApp.Controllers
{
    public class SalesOrdersController : Controller
    {
        private SalesOrdersRepository _salesOrdersRepository;
        public SalesOrdersController()
        {
            _salesOrdersRepository = new SalesOrdersRepository();
        }

        public ActionResult Index()
        {
            IEnumerable<SalesOrders> salesOrders = _salesOrdersRepository.GetAllSalesOrders();
            return View(salesOrders);
        }

       
        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SalesOrders salesOrders)
        {
            try
            {
                _salesOrdersRepository.AddSalesOrder(salesOrders);
                TempData["success"] = "SalesOrders created successfully";
                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                return View(ex);
            }
        }

        public ActionResult Edit(int id)
        {
            SalesOrders salesOrders = _salesOrdersRepository.GetSalesOrder(id);
            return View(salesOrders);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SalesOrders salesOrders)
        {
            try
            {
                _salesOrdersRepository.UpdateSalesOrder(salesOrders);
                TempData["success"] = "SalesOrders updated successfully";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                if (_salesOrdersRepository.DeleteSalesOrder(id))
                {
                    ViewBag.AlertMsg = "Deleted successfully";
                }
                TempData["success"] = "SalesOrders deleted successfully";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

InternTestWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Welcome";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

InternTestWebApp/Views/SalesOrders/Create.cshtml
@model InternTestWebApp.Models.SalesOrders
@{
    ViewData["Title"] = "Create";
}
<div class="row pt-4">
    <div class="col-6">
        <h2 class="text-primary">Create Sales Order</h2>
    </div>
</div>
<br />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SalesOrder" class="control-label"></label>
                <input asp-for="SalesOrder" class="form-control" />
                <span asp-validation-for="SalesOrder" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SalesOrderItem" class="control-label"></label>
                <input asp-for="SalesOrderItem" class="form-control" />
                <span asp-validation-for="SalesOrderItem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WorkOrder" class="control-label"></label>
                <input asp-for="WorkOrder" class="form-control" />
                <span asp-validation-for="WorkOrder" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductID" class="control-label"></label>
                <input asp-for="ProductID" class="form-control" />
                <span asp-validation-for="ProductID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductDescription" class="control-label"></label>
                <input asp-for="ProductDescription" class="form-control" />
                <span asp-validation-for="ProductDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderQuantity" class="control-label"></label>
                <input asp-for="OrderQuantity" class="form-control" />
                <span asp-validation-for="OrderQuantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderStatus" class="control-label"></label>
                <input asp-for="OrderStatus" class="form-control" />
                <span asp-validation-for="OrderStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Timestamp" class="control-label"></label>
                <input asp-for="Timestamp" class="form-control" />
                <span asp-validation-for="Timestamp" class="text-danger"></span>
            </div>
            <br />
            <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
            <a asp-action="Index" class="btn btn-secondary" style="width:150px">
                Back to List
            </a>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

InternTestWebApp/Views/SalesOrders/Edit.cshtml
@model InternTestWebApp.Models.SalesOrders
@{
    ViewData["Title"] = "Edit";
}
<div class="row pt-4">
    <div class="col-6">
        <h2 class="text-primary">Edit Sales Order</h2>
    </div>
</div>
<br />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="SalesOrder" class="control-label"></label>
                <input asp-for="SalesOrder" class="form-control" />
                <span asp-validation-for="SalesOrder" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SalesOrderItem" class="control-label"></label>
                <input asp-for="SalesOrderItem" class="form-control" />
                <span asp-validation-for="SalesOrderItem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WorkOrder" class="control-label"></label>
                <input asp-for="WorkOrder" class="form-control" />
                <span asp-validation-for="WorkOrder" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductID" class="control-label"></label>
                <input asp-for="ProductID" class="form-control" />
                <span asp-validation-for="ProductID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductDescription" class="control-label"></label>
                <input asp-for="ProductDescription" class="form-control" />
                <span asp-validation-for="ProductDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderQuantity" class="control-label"></label>
                <input asp-for="OrderQuantity" class="form-control" />
                <span asp-validation-for="OrderQuantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderStatus" class="control-label"></label>
                <input asp-for="OrderStatus" class="form-control" />
                <span asp-validation-for="OrderStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Timestamp" class="control-label"></label>
                <input asp-for="Timestamp" class="form-control" />
                <span asp-validation-for="Timestamp" class="text-danger"></span>
            </div>
            <br/>
            <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
            <a asp-action="Index" class="btn btn-secondary" style="width:150px">
                Back to List
            </a>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

InternTestWebApp/Views/SalesOrders/Index.cshtml
@model IEnumerable<InternTestWebApp.Models.SalesOrders>
@{
    ViewData["Title"] = "Detail";
}

<div class="row pt-4">
    <div class="col-6">
        <h2 class="text-primary">Sales Order Detail</h2>
    </div>
    <div class="col-6 text-end">
        <a asp-action="Create" class="btn btn-primary">
            <i class="bi bi-plus-circle"></i> &nbsp; Create New Order
        </a>
    </div>
</div>
<br />
<br />

<table class="table table-bordered table-striped" style="width: 100%">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SalesOrder)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SalesOrderItem)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WorkOrder)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderQuantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Timestamp)
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SalesOrder)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SalesOrderItem)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WorkOrder)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductDescription)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderQuantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderStatus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Timestamp)
                <td>
                        
                    <div class="w-100 btn-group" role="group">
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-primary mx-2" })
                            @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger mx-2", onclick = "return confirm('Are sure wants to delete?');" })
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

InternTestWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InternTestWebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="SalesOrders" asp-action="Index">Detail</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - InternTestWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

InternTestWebApp/Views/Shared/_Notification.cshtml
﻿@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}